[tool.poetry]
name = "msys2-autobuild"
version = "0.1.0"
description = ""
authors = ["Christoph Reiter <reiter.christoph@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.1"
PyGithub = "^1.57.0"
tabulate = "^0.9.0"
requests = "^2.28.1"
requests-cache = "^1.0.0b0"

[tool.poetry.dev-dependencies]
mypy = "1.0.1"
flake8 = "^6.0.0"
types-tabulate = "^0.9.0.0"
types-requests = "^2.25.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
