name: 'build'

on:
  workflow_dispatch:
  repository_dispatch:
    types: [manual-build]
  schedule:
    - cron: '0 0/4 * * *'

env:
  CI: true
  PY_COLORS: 1

jobs:

  build:
    runs-on: windows-latest
    continue-on-error: true
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: actions/checkout@v2

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: base-devel msys2-devel mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain git python python-pip

    - name: Install deps
      run: |
        python -m pip install --user -r requirements.txt

    - name: Show build queue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python autobuild.py show

    - name: Clean up assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python autobuild.py clean-assets

    - name: Process build queue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export PACKAGER="CI (msys2-devtools/${GITHUB_SHA::8}/${GITHUB_RUN_ID})"
        mkdir -p _tmp/assets
        python autobuild.py build _tmp

    - if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        path: _tmp/assets/*

  staging:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/download-artifact@v2

    - uses: eine/tip@master
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'staging-msys'
        files: artifact/msys/*.tar.*

    - uses: eine/tip@master
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'staging-mingw'
        files: artifact/mingw/*.tar.*

    - uses: eine/tip@master
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'staging-failed'
        files: artifact/failed/*.failed
