name: 'build'

on:
  workflow_dispatch:
  repository_dispatch:
    types: [manual-build]
  schedule:
    - cron: '0 0/4 * * *'

env:
  CI: true
  PY_COLORS: 1

jobs:

  build:
    runs-on: windows-latest
    continue-on-error: true
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        update: true
        install: base-devel msys2-devel mingw-w64-x86_64-toolchain mingw-w64-i686-toolchain

    - name: Check install
      run: |
        msys2 -c 'pacman -Qkq'

    - name: Install deps
      run: |
        python -m pip install --user -r requirements.txt

    - name: Show build queue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python autobuild.py show

    - name: Clean up assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python autobuild.py clean-assets

    - name: Process build queue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $env:PACKAGER='CI (msys2-devtools/' + $env:GITHUB_SHA.Substring(0, 8) + '/' + $env:GITHUB_RUN_ID + ')'
        $BUILD_ROOT=((Get-Location).Drive.Root) + '_'
        $MSYS2_ROOT=(msys2 -c 'cygpath -w /')
        python autobuild.py build "$MSYS2_ROOT" "$BUILD_ROOT"